### ISSUE TITLE
Update `waitUntil` signature to support selectors.

### ISSUE THREAD

**Issue by rwjblue** [cibernox/ember-native-dom-helpers#109]
I find that the most common thing I do in a `waitUntil` is something like:

```js
await waitUntil(() => find('.some-selector'))
```

I am proposing that we allow the following:

```js
await waitUntil('.some-selector');
```

This would work by detecting a string argument, and expanding it into the `() => find(selector))` version.

Thoughts?

**Comment by cibernox** [comment]
The caveat with this is to consider if we should allow the same options `find` does. That is, passing a second argument of type `HTMLElement` to narrow the search in.

Alternatively, we could accept passing a function and any number of arguments, and invoke that function with them, similarly to how Ember.run works.

`waitUntil(find, '.selector', context)`

**Comment by Turbo87** [comment]
@cibernox IMHO if you need that second argument you can just use the long form version with the arrow function

**Comment by cibernox** [comment]
Current suggestion: Implement a `waitFor(selector, opts)` method instead of make the signature of waitUntil more complex.

Possible usages:

- `waitFor('.selector')` => `waitUntil(() => !!find('.selector'))`
- `waitFor('.selector', { count: 10 })` => `waitUntil(() => findAll('.selector').length === 10)`
- `waitFor('.selector', { timeout: 2000 })` => `waitUntil(() => !!find('.selector'), { timeout: 2000 })`
