### ISSUE TITLE
Behaviour of `find` when no element matches the result

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-native-dom-helpers#13]
At the moment the logic is that if the helper finds only one element matching the selector, it will return the Node but if there is more it will returns a `NodeList`. So far so good.

But when there is no results, right now it returns an empty `NodeList`. I wonder if this is expected or it should return `undefined/null` in that case.

/cc @rwjblue @pixelhandler What do you think it's better/more intuitive?

**Comment by pixelhandler** [comment]
@cibernox I think an empty NodeList is comparable to how the (acceptance)`find` helper works using jQuery. An empty wrapped set is returned when no elements match the query. So `find('.nada').length === 0` may be ok. However, the `findWithAssert` is interesting since an empty result would raise an error. Perhaps we need to add that helper as well. 

In my opinion null would be better than and empty NodeList.

**Comment by Padchi** [comment]
`undefined/null` when it's no results would be really good. Right now there is no a clear way (maybe it isn't any way) to see if a element is defined or not with `find()` like `assert.equal(this.$(.'foo').length, 1)`;

**Comment by cibernox** [comment]
I agree, I prefer `null. I just want to get one last confirmation from @rwjblue. If we are going to change that, the sooner the better.

**Comment by Padchi** [comment]
I prefer `undefined` because for me, if the element is not there it is undefined, just like a regular function/var what ever. But tbh i don't care, i just want to be able to check if a element exist or not with `find() and get rid of all my jQuery references. Can't find anything in @rwjblue RFC about this so we wait for him like you said :)

**Comment by pixelhandler** [comment]
@cibernox See the PR, #15 I proposed that we return `null`, `HTMLElement` or `NodeList` and also mentioned an alternative on two helpers instead of one.

The main feature of the find helper is searching within the test DOM only. internally it behaves like querySelector or querySelectorAll, so we could change to find and findAll if we want the helper to behave more like these DOM APIs.

**Comment by pixelhandler** [comment]
@Padchi `null` is what `document.querySelector` returns. So I think that is better than `undefined`.

**Comment by pixelhandler** [comment]
@rwjblue for now find could return `null` for an empty query. Alternatively we could use two helpers, `find(string) null | HTMLElement` and `findAll(string) NodeList[]` (the node list may be empty when the query has no matching result.

What do you think?

**Comment by pixelhandler** [comment]
See #18 for the `find` and `findAll` alternative

**Comment by rwjblue** [comment]
FWIW, the testing RFC proposes `find` and `findAll` so that the mental model is much simplified and the return values are consistent.  

IMO #18 is definitely on the right path...
