### ISSUE TITLE
Use `key` instead of `keyCode` for `keyEvent` helper?

### ISSUE THREAD

**Issue by patrickberkeley** [cibernox/ember-native-dom-helpers#136]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), `keyCode` is deprecated in favor of `key`. Thoughts on updating the `keyEvent` helper to accommodate that?

**Comment by cibernox** [comment]
I am aware. However now the helpers of this projects are becoming "official" and have been copied into https://github.com/emberjs/ember-test-helpers/.

During the migration I left a comment [here](https://github.com/emberjs/ember-test-helpers/pull/258#discussion_r155963086) and there is an issue to do it soon: https://github.com/emberjs/ember-test-helpers/issues/265

Since now many helpers of this addon are becoming "official" inside `@ember/test-helpers`, if we fix it it will be in that repo. Those helpers here will be deprecated and eventually removed.

**Comment by patrickberkeley** [comment]
Gotcha. Thanks for the info, I didn't realize `ember-native-dom-helpers` is becoming part of `ember-test-helpers`.
