### ISSUE TITLE
IE11 fillIn double fires oninput event

### ISSUE THREAD

**Issue by john-griffin** [cibernox/ember-native-dom-helpers#140]
We recently migrated our app from `ember-one-way-controls` to native inputs and `ember-native-dom-helpers` in our integration tests to keep the tests working. `fillIn` on works great on other browsers but when we test against IE11 we are finding that it double fires any events wired up to `oninput`. This does not happen when running in the real browser.

**Comment by cibernox** [comment]
Sounds weird. Can you provide add failing test and I'll take it from there.

Although to be honest, since `ember-test-helpers` now has included all the helpers in this repo (but `find` and `findAll`), it might be worth it trying to reproduce it there.

**Comment by john-griffin** [comment]
Ah ok, yes I can see reading your post [here](https://dockyard.com/blog/2018/01/11/modern-ember-testing) that this is now the wrong place to discuss this. The guides and ember-one-way-controls readme were still pointing here, sorry about that.

**Comment by rwjblue** [comment]
FWIW, this is an issue that I've seen as well.  It largely happens when IE11 is under somewhat heavy load (and is not reproducible 100% of the time).  For example, in VM's locally I have yet to run across this issue in either Ember itself or in `@ember/test-helpers` but when ran in BrowserStack's VM's it "randomly" sends `input` twice.

**Comment by john-griffin** [comment]
@rwjblue thanks for the details. We are seeing it on saucelabs and on a desktop windows computer.
