### ISSUE TITLE
Support for sizzle-selectors

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-native-dom-helpers#32]
I've decided to unify #26 and #23 into this single issue.

I've tried to adapt the test suites of `ember-basic-dropdown`, `ember-power-select` and `ember-calendar` to use this library and I've found a few places where this library cannot be a drop-in replacement because CSS3 selectors are more limited than those availables in jquery (which uses the sizzle selector engine)

Those cases include:

- `$('.option:contains("Portugal")').click()` !== `click('.option:contains("Portugal")')`
- `$optionsRoot.find('> .options-group-name')` !== `find('> .options-group-name', optionsRoot)`
- `$('.select-option:eq(2)')` !== `find('.select-option:eq(2)')` (although === to `findAll('.select-option')[2]`

Other cases I don't use but I also know that are not supported:

- `:even`/`:odd`
- `[attr!=value]`
- `:has(subSelector)`

The question is whether or not we want to stick to basic CSS3 selectors only or allow the superset that sizzles supports to ease the transition from jquery-based selectors. Sizzle would only be included in the test-support tree, so it would not impact the size of the app itself.
The returned results would still be native `HTMLElement`s or `NodeList`s.

**Comment by rwjblue** [comment]
FWIW, this dovetails with a conversation that @machty and I had. I am not 100% certain this is the right path, but I think we should implement and experiment. 

My primary constraints are that the sizzle engine needs to be fully encapsulated from the running application code. Having it present in tests for use by this library seems fine, but having accidentally ambiently available to app code would set folks up for failure (tests would pass, but prod would be broken). I haven't looked into how sizzle is distributed, so I'm not sure how easy/hard this would be.

**Comment by Turbo87** [comment]
IMHO we should limit this to CSS3 selectors and if you want to use sizzle then use jquery directly. Otherwise there are also helpers like ember-test-selectors that remove most of the need for sizzle.

**Comment by pixelhandler** [comment]
I’m not that fond of trying to mimic Sizzle, I don’t think the goal is drop in replacement using native dom helpers. When `find`/`findAll` won’t just work, within the body of a given test, the developer can just use Sizzle instead of `find`. Then later can adopt native dom helpers’s find behaviors by using CSS selectors. Since find can receive an HTMLElement the work around could be to use sizzle to find an element, then pass to found element into find instead of the selector ( https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/-private/get-element.js#L5 ) for the any special test behavior that find provides.

**Comment by cibernox** [comment]
I decided to close this issue. Seems that sizzle pseudo selectors are being deprecated even in jQuery.

There is two main selectors people use in the wild: `:eq(N)` (which is trivial to implement y doing `findAll()[N]`) and `:contains`, which is a bit verbose but may or may not deserve a standalone helper, but certainly not an implementation that parses pseudoselectors.
