### ISSUE TITLE
Simulate Ctrl + Delete in Acceptance tests

### ISSUE THREAD

**Issue by yrtejas** [cibernox/ember-native-dom-helpers#92]
I am trying to do a control + delete on one of my elements. I queried it on [SO](https://stackoverflow.com/questions/45373016/simulate-ctrl-cmd-delete-keyevent-combination-in-ember-test). My code is not deleting the element:

test('multi-press', async function(assert){
 await click(<selector name>);
 await triggerEvent(<selector name>, "keydown", {ctrlKey: true, keyCode: 46});
 await triggerEvent(<selector name>, "keyup", {ctrlKey: false, keyCode: 46});}

Please suggest! Help Needed!

**Comment by cibernox** [comment]
@yrtejas Did you try `keyEvent('.somewhere', 'keydown', 46, { ctrlKey: true })`?

**Comment by cibernox** [comment]
However be aware that this event WILL NOT delete the text, it will only simulate the event but the browser will not delete the text for real because it is a synthetic event. It is impossible to trigger any event that makes the browser delete for real. 
You'd have to clear the text input yourself (`find('.input').value = ''`) and then fire the event.

**Comment by yrtejas** [comment]
I got this error. 

` ✘ Error: Attempted to handle event `becameError` on <element:oqq4jr61> while in state root.deleted.saved.  at Class.exception (serve://dist/assets/test-support.js:8340:44)
         expected true`.

I believe your code worked but I guess the error is an Ember data issue.

**Comment by cibernox** [comment]
Agree, that has nothing to do with the test helper.
